version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortner-backend
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    entrypoint: >
      sh -c "
      apk add --no-cache curl &&
      until curl -s db:5432; do
        echo 'Waiting for the database...';
        sleep 2;
      done;
      yarn start"

  db:
    image: postgres:14
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  